#!/usr/bin/env bash
# script to install and setup nginx
apt-get update
apt-get install -y nginx
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF
service nginx restart
echo "Hello World!" > /var/www/html/index.html
