#!/usr/bin/env bash
# Installs nginx web server

# Update package list and install Nginx
apt-get update
apt-get install -y nginx

# Start Nginx service
service nginx start

# Create a default index.html page
echo "Hello World!" > /var/www/html/index.html

# Create a custom 404 error page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx server block
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html;

    # Redirection configuration
    location /redirect_me {
        return 301 https://twitter.com/Awwal_Temidire;
    }

    # Custom 404 error page
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply the new configuration
service nginx restart

